8304143: Exclude duplicated class on linux, aix, and macos
openjdk/jdk8u pull request #40
Opened 2023-03-14 14:54 UTC by adamfarley

This change excludes the duplicated class SystemMetrics, and ensures we use the platform-specific version of the SystemMetrics class instead.

2023-03-14 14:56 UTC, jerboaa commented
@adamfarley Please enable GHA.

2023-03-14 14:56 UTC, adamfarley commented
I thought I did.

2023-03-14 14:58 UTC, adamfarley commented
It seems to be running something. Is this not GHA?

https://github.com/adamfarley/jdk8u/actions/runs/4417066915

2023-03-14 15:07 UTC, jerboaa commented
> It seems to be running something. Is this not GHA?
> 
> https://github.com/adamfarley/jdk8u/actions/runs/4417066915

Yes, that's GHA. I mentioned it, because #37 didn't have it enabled causing the breakage :-(

2023-03-14 15:17 UTC, adamfarley commented
> > It seems to be running something. Is this not GHA?
> > https://github.com/adamfarley/jdk8u/actions/runs/4417066915
> 
> Yes, that's GHA. I mentioned it, because #37 didn't have it enabled causing the breakage :-(

Fair enough. Better to be safe than sorry. Again. :(

2023-03-14 15:21 UTC, jerboaa requested changes
We should only exclude the class on Linux. That's the OS where the `SystemMetrics` class is actually implemented. In order to solve the resulting build break on Mac and AIX, we should revert additions of the `null` returning classes there. Perhaps with #39.

I propose the following course of action to fix it:

1. Only exclude `SystemMetrics.java` on Linux from the `solaris` directory in this PR. Make this PR dependent on #39 (dependent pull request).
2. Revert stub impl additions on Mac OS X and AIX with #39.

@gnu-andrew  Thoughts?

2023-03-14 15:40 UTC, jerboaa commented
> We should only exclude the class on Linux. That's the OS where the `SystemMetrics` class is actually implemented. In order to solve the resulting build break on Mac and AIX, we should revert additions of the `null` returning classes there. Perhaps with #39.
> 
> I propose the following course of action to fix it:
> 
>     1. Only exclude `SystemMetrics.java` on Linux from the `solaris` directory in this PR. Make this PR dependent on #39 (dependent pull request).
>     2. Revert stub impl additions on Mac OS X and AIX with #39.

Change of plan. Do all of it here, and use JDK-8304053 as the bug to integrate.

2023-03-14 15:42 UTC, gnu-andrew commented
Ok, this just changed while I was looking at it :)

I think the current version incorporates #39 now, so we just need this one?

This seems to relate to what I was referring to in [my comment](https://bugs.openjdk.org/browse/JDK-8303828?focusedCommentId=14565610&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14565610) on the bug about 11u. 11u uses `src/unix` for the generic versions and platform-specific overrides. On 8u, `src/solaris` is that generic version unless we opt out.

So I would also remove the unused `unix` copy of the file here, assuming builds aren't broken, and refer to both bug IDs.

2023-03-14 16:07 UTC, adamfarley commented
Sure thing. I've changed the PR title as requested, and will remove the unix stub class. Will not squash or force push.

2023-03-14 16:16 UTC, adamfarley commented on jdk/make/CompileJavaClasses.gmk
> +     EXFILES += $(JDK_TOPDIR)/src/solaris/classes/jdk/internal/platform/SystemMetrics.java
Sure. 1 moment.

2023-03-14 16:19 UTC, adamfarley commented on jdk/make/CompileJavaClasses.gmk
> +     EXFILES += $(JDK_TOPDIR)/src/solaris/classes/jdk/internal/platform/SystemMetrics.java
Done.

2023-03-14 16:25 UTC, jerboaa approved these changes
Looks good. Let's wait for a clean GHA run this time before we integrate :)

2023-03-14 16:25 UTC, jerboaa commented on jdk/make/CompileJavaClasses.gmk
> +     EXFILES += $(JDK_TOPDIR)/src/solaris/classes/jdk/internal/platform/SystemMetrics.java
Thanks!

2023-03-14 17:02 UTC, gnu-andrew commented
FYI: Linux builds are broken without this too:

~~~
/home/andrew/projects/openjdk/upstream/jdk8u-dev/jdk/src/linux/classes/jdk/internal/platform/SystemMetrics.java:27: error: duplicate class: jdk.internal.platform.SystemMetrics
public class SystemMetrics {
~~~

so I'm not going to promote b06 from last week, but will instead make b06 the promotion at the end of this week, with this fix. I'll write similar to the mailing list.

2023-03-15 12:57 UTC, jerboaa commented
@adamfarley The bug is approved. GHA looks OK. Please `/integrate`. Thanks!

2023-03-15 14:11 UTC, closed without merging